name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_OPTIONS: --max_old_space_size=6144 # assert node processes to use 6Gb (GA limit = 7Gb)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 'lts/*']

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Yarn Install
        run: yarn install
      - run: cp .env.test .env
      - name: Run tests
        run: NODE_ENV=test yarn c:test
      - name: Run Type
        run: NODE_ENV=test yarn c:type
      - name: Run Lint
        run: NODE_ENV=test yarn c:lint
